%> @file  workflows_paper.m
%> @brief Script that contains the sequence of modules used for EEG and audio preprocessing for the manuscript

%> history
%> 2019/07/24 updated comments
%% erp processing
pipeline_erp = struct;
pipeline_erp.task = 'tonestimuli';
pipeline_erp.sname = 'wf_erp';
pipeline_erp.pp   = {'pp_ft_reref_mastoids',...
                     'pp_ft_lowpass30_fs512',...
                     'pp_ft_linenoiseremoval',...
                     'pp_ft_resample128',...
                     'pp_ft_highpass01_fs128',...
                     'pp_ft_reref_bipolareog',...
                     'pp_ft_segmenttrials_erp_tone_beep',...
                     'pp_ft_eogdenoise',...
                     'pp_ft_toi_erp'};

pipeline_dg_erp = struct;
pipeline_dg_erp.task = 'tonestimuli';
pipeline_dg_erp.sname = 'wf_dg_erp';
pipeline_dg_erp.pp = {'pp_ft_reref_mastoids',...
                     'pp_ft_lowpass30_fs512',...
                     'pp_ft_linenoiseremoval',...
                     'pp_ft_resample128',...
                     'pp_ft_highpass01_fs128',...
                     'pp_ft_reref_bipolareog',...
                     'pp_ft_segmenttrials_erp_dg',...
                     'pp_ft_eogdenoise',...
                     'pp_ft_toi_erp'};

%% itpc                  
pipeline_dg_itpc = struct;
pipeline_dg_itpc.task = 'tonestimuli';
pipeline_dg_itpc.sname = 'wf_dg_itpc';
pipeline_dg_itpc.pp = {'pp_ft_reref_mastoids',...
                     'pp_ft_lowpass60_fs512',...
                     'pp_ft_linenoiseremoval',...
                     'pp_ft_resample128',...
                     'pp_ft_highpass01_fs128',...
                     'pp_ft_reref_bipolareog',...
                     'pp_ft_segmenttrials_efr'};

%% eeg data from selective attention experiment                  
pipeline_eeg_attention = struct;
pipeline_eeg_attention.task = 'selectiveattention';
pipeline_eeg_attention.sname = 'wf_eeg_att';                               
pipeline_eeg_attention.pp = {'pp_ft_reref_mastoids',... 
                     'pp_ft_lowpass30_fs512',... 
                     'pp_ft_resample64',... 
                     'pp_ft_highpass05_fs64_attention',... 
                     'pp_ft_reref_bipolareog',... 
                     'pp_ft_segmenttrials_attention',...
                     'pp_ft_appenddatafromsessions_attention',...
                     'pp_ft_eogdenoise',...
                     'pp_ft_highpass1_fs64_attention',...
                     'pp_ft_lowpass9_fs64_attention',...
                     'pp_ft_toi_attention'};

pipeline_eeg_attention_st_denoising = struct;
pipeline_eeg_attention_st_denoising.task = 'selectiveattention';
pipeline_eeg_attention_st_denoising.sname = 'wf_eeg_att_stdenoising';                               
pipeline_eeg_attention_st_denoising.pp = {'pp_ft_reref_mastoids',... 
                     'pp_ft_lowpass30_fs512',... 
                     'pp_ft_resample64',... 
                     'pp_ft_highpass05_fs64_attention',... 
                     'pp_ft_reref_bipolareog',... 
                     'pp_ft_segmenttrials_attention',...
                     'pp_ft_appenddatafromsessions_attention',...
                     'pp_ft_eogdenoise_attention_st',...
                     'pp_ft_highpass1_fs64_attention',...
                     'pp_ft_lowpass9_fs64_attention',...
                     'pp_ft_toi_attention'};
 
%% audio data from selective attention experiment                  
pipeline_aud_attention = struct;
pipeline_aud_attention.task = 'selectiveattention';
pipeline_aud_attention.sname = 'wf_aud_att'; 
pipeline_aud_attention.pp = ...
                    {'pp_aud_average',... 
                     'pp_aud_lowpass6000_44100',... 
                     'pp_aud_resample12000_44100',... 
                     'pp_aud_gammatone',... 
                     'pp_aud_fullwave_rectify',...
                     'pp_aud_powerlaw03',... 
                     'pp_aud_average',...
                     'pp_aud_lowpass256_12000',...
                     'pp_aud_resample512_12000',...
                     'pp_aud_lowpass30_512',...
                     'pp_aud_resample64_512',...
                     'pp_aud_highpass1_64',...
                     'pp_aud_lowpass9_64',...
                     'pp_aud_toi_attention'};
     

pipeline_aud_attention_multiple_c = struct;
pipeline_aud_attention_multiple_c.task = 'selectiveattention';
pipeline_aud_attention_multiple_c.sname = 'wf_aud_att_mc'; 
pipeline_aud_attention_multiple_c.pp = ...
                    {'pp_aud_average',... 
                     'pp_aud_lowpass6000_44100',... 
                     'pp_aud_resample12000_44100',... 
                     'pp_aud_gammatone',... 
                     'pp_aud_fullwave_rectify',...
                     'pp_aud_powerlaw_sweep_01_1',... 
                     'pp_aud_average',...
                     'pp_aud_lowpass256_12000',...
                     'pp_aud_resample512_12000',...
                     'pp_aud_lowpass30_512',...
                     'pp_aud_resample64_512',...
                     'pp_aud_highpass1_64',...
                     'pp_aud_lowpass9_64',...
                     'pp_aud_toi_attention'};
     
